language: python
python:
  - "2.7"
install:
  - pip install flake8
script:
  - pip install Django
  - django-admin.py startproject --template=. mysite
  - cd mysite
  - chmod +x manage.py
  - pip install -r requirements.txt
  - ./manage.py syncdb --noinput
  - ./manage.py loaddata sites
  - ./manage.py validate
  - flake8 mysite
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ae96ef4935f589eb9d9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
